# Generated by Django 2.1.7 on 2019-12-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20191224_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
