# Generated by Django 2.1.7 on 2019-12-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='titile',
            new_name='title',
        ),
        migrations.AddField(
            model_name='carousel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('deleted', 'Silindi')], default='draft', max_length=10),
        ),
    ]
