# Generated by Django 2.1.7 on 2019-12-25 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20191224_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
